// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Observe(Observation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Resolve(ResolutionQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Project(ProjectionQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Validate(Validation);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Observed(ObservationResult);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Resolved(ResolutionResult);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Projected(Projection);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Validated(ValidationReport);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestRejected(RejectedRequest);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Domain(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NetworkAddress(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RecordValue(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UniformResourceLocator(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationTarget(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ResolutionScope {
    Public,
    Internal,
    Intelligent,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RecordKind {
    AddressV4,
    AddressV6,
    CanonicalName,
    Text,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RedirectStatus {
    Permanent,
    Temporary,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum PathTreatment {
    Preserve,
    Replace,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ProjectionScope {
    PublicRecords,
    RedirectRules,
    Everything,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResolutionQuery {
    pub name: DomainName,
    pub resolution_scope: ResolutionScope,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Address {
    pub name: DomainName,
    pub address: NetworkAddress,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResolutionResult {
    pub query: ResolutionQuery,
    pub addresses: Vec<Address>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainQuery(Option<DomainName>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainListing(Vec<DomainName>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Delegation {
    pub delegation_name: DelegationName,
    pub domain_name: DomainName,
    pub delegation_target: DelegationTarget,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationQuery(Option<DomainName>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DelegationListing(Vec<Delegation>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainNameSystemRecord {
    pub name: DomainName,
    pub record_kind: RecordKind,
    pub value: RecordValue,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RedirectRule {
    pub source: DomainName,
    pub target: UniformResourceLocator,
    pub redirect_status: RedirectStatus,
    pub path_treatment: PathTreatment,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ProjectionQuery {
    pub domain: DomainName,
    pub projection_scope: ProjectionScope,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Projection {
    pub query: ProjectionQuery,
    pub records: Vec<DomainNameSystemRecord>,
    pub redirects: Vec<RedirectRule>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Observation {
    Domains(Domains),
    Delegations(Delegations),
    Projection(Project),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Domains(DomainQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Delegations(DelegationQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Validation(Domain);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ObservationResult {
    Domains(DomainListing),
    Delegations(DelegationListing),
    Projection(Projection),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RejectionReason {
    DomainUnknown,
    DelegationUnknown,
    ProjectionUnavailable,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RejectedRequest {
    pub operation: OperationKind,
    pub reason: RejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OperationKind {
    Observe,
    Resolve,
    Project,
    Validate,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ValidationReport(Vec<ValidationFinding>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ValidationFinding {
    pub severity: FindingSeverity,
    pub message: Message,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum FindingSeverity {
    Notice,
    Warning,
    Error,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Message(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Observe(Observe),
    Resolve(Resolve),
    Project(Project),
    Validate(Validate),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Observed(Observed),
    Resolved(Resolved),
    Projected(Projected),
    Validated(Validated),
    RequestRejected(RequestRejected),
}

#[rustfmt::skip]
impl Observe {
    pub fn new(payload: Observation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Observation {
        &self.0
    }
    pub fn into_payload(self) -> Observation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Observation> for Observe {
    fn from(payload: Observation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Resolve {
    pub fn new(payload: ResolutionQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ResolutionQuery {
        &self.0
    }
    pub fn into_payload(self) -> ResolutionQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<ResolutionQuery> for Resolve {
    fn from(payload: ResolutionQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Project {
    pub fn new(payload: ProjectionQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ProjectionQuery {
        &self.0
    }
    pub fn into_payload(self) -> ProjectionQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<ProjectionQuery> for Project {
    fn from(payload: ProjectionQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Validate {
    pub fn new(payload: Validation) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Validation {
        &self.0
    }
    pub fn into_payload(self) -> Validation {
        self.0
    }
}
#[rustfmt::skip]
impl From<Validation> for Validate {
    fn from(payload: Validation) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Observed {
    pub fn new(payload: ObservationResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ObservationResult {
        &self.0
    }
    pub fn into_payload(self) -> ObservationResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<ObservationResult> for Observed {
    fn from(payload: ObservationResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Resolved {
    pub fn new(payload: ResolutionResult) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ResolutionResult {
        &self.0
    }
    pub fn into_payload(self) -> ResolutionResult {
        self.0
    }
}
#[rustfmt::skip]
impl From<ResolutionResult> for Resolved {
    fn from(payload: ResolutionResult) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Projected {
    pub fn new(payload: Projection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Projection {
        &self.0
    }
    pub fn into_payload(self) -> Projection {
        self.0
    }
}
#[rustfmt::skip]
impl From<Projection> for Projected {
    fn from(payload: Projection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Validated {
    pub fn new(payload: ValidationReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ValidationReport {
        &self.0
    }
    pub fn into_payload(self) -> ValidationReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ValidationReport> for Validated {
    fn from(payload: ValidationReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestRejected {
    pub fn new(payload: RejectedRequest) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RejectedRequest {
        &self.0
    }
    pub fn into_payload(self) -> RejectedRequest {
        self.0
    }
}
#[rustfmt::skip]
impl From<RejectedRequest> for RequestRejected {
    fn from(payload: RejectedRequest) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Domain {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Domain {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DomainName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DomainName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NetworkAddress {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NetworkAddress {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RecordValue {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RecordValue {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UniformResourceLocator {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for UniformResourceLocator {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DelegationName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DelegationName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DelegationTarget {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DelegationTarget {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DomainQuery {
    pub fn new(payload: Option<DomainName>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<DomainName> {
        &self.0
    }
    pub fn into_payload(self) -> Option<DomainName> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<DomainName>> for DomainQuery {
    fn from(payload: Option<DomainName>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DomainListing {
    pub fn new(payload: Vec<DomainName>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<DomainName> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<DomainName> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<DomainName>> for DomainListing {
    fn from(payload: Vec<DomainName>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DelegationQuery {
    pub fn new(payload: Option<DomainName>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<DomainName> {
        &self.0
    }
    pub fn into_payload(self) -> Option<DomainName> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<DomainName>> for DelegationQuery {
    fn from(payload: Option<DomainName>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DelegationListing {
    pub fn new(payload: Vec<Delegation>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<Delegation> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<Delegation> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<Delegation>> for DelegationListing {
    fn from(payload: Vec<Delegation>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Domains {
    pub fn new(payload: DomainQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DomainQuery {
        &self.0
    }
    pub fn into_payload(self) -> DomainQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<DomainQuery> for Domains {
    fn from(payload: DomainQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Delegations {
    pub fn new(payload: DelegationQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DelegationQuery {
        &self.0
    }
    pub fn into_payload(self) -> DelegationQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<DelegationQuery> for Delegations {
    fn from(payload: DelegationQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Validation {
    pub fn new(payload: Domain) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Domain {
        &self.0
    }
    pub fn into_payload(self) -> Domain {
        self.0
    }
}
#[rustfmt::skip]
impl From<Domain> for Validation {
    fn from(payload: Domain) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ValidationReport {
    pub fn new(payload: Vec<ValidationFinding>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ValidationFinding> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ValidationFinding> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ValidationFinding>> for ValidationReport {
    fn from(payload: Vec<ValidationFinding>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Message {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for Message {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Observation {
    pub fn domains(payload: DomainQuery) -> Self {
        Self::Domains(Domains::new(payload))
    }
    pub fn delegations(payload: DelegationQuery) -> Self {
        Self::Delegations(Delegations::new(payload))
    }
    pub fn projection(payload: ProjectionQuery) -> Self {
        Self::Projection(Project::new(payload))
    }
}

#[rustfmt::skip]
impl ObservationResult {
    pub fn domains(payload: Vec<DomainName>) -> Self {
        Self::Domains(DomainListing::new(payload))
    }
    pub fn delegations(payload: Vec<Delegation>) -> Self {
        Self::Delegations(DelegationListing::new(payload))
    }
    pub fn projection(payload: Projection) -> Self {
        Self::Projection(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn observe(payload: Observation) -> Self {
        Self::Observe(Observe::new(payload))
    }
    pub fn resolve(payload: ResolutionQuery) -> Self {
        Self::Resolve(Resolve::new(payload))
    }
    pub fn project(payload: ProjectionQuery) -> Self {
        Self::Project(Project::new(payload))
    }
    pub fn validate(payload: Validation) -> Self {
        Self::Validate(Validate::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn observed(payload: ObservationResult) -> Self {
        Self::Observed(Observed::new(payload))
    }
    pub fn resolved(payload: ResolutionResult) -> Self {
        Self::Resolved(Resolved::new(payload))
    }
    pub fn projected(payload: Projection) -> Self {
        Self::Projected(Projected::new(payload))
    }
    pub fn validated(payload: ValidationReport) -> Self {
        Self::Validated(Validated::new(payload))
    }
    pub fn request_rejected(payload: RejectedRequest) -> Self {
        Self::RequestRejected(RequestRejected::new(payload))
    }
}

#[rustfmt::skip]
impl From<Domains> for Observation {
    fn from(payload: Domains) -> Self {
        Self::Domains(payload)
    }
}

#[rustfmt::skip]
impl From<Delegations> for Observation {
    fn from(payload: Delegations) -> Self {
        Self::Delegations(payload)
    }
}

#[rustfmt::skip]
impl From<Project> for Observation {
    fn from(payload: Project) -> Self {
        Self::Projection(payload)
    }
}

#[rustfmt::skip]
impl From<DomainListing> for ObservationResult {
    fn from(payload: DomainListing) -> Self {
        Self::Domains(payload)
    }
}

#[rustfmt::skip]
impl From<DelegationListing> for ObservationResult {
    fn from(payload: DelegationListing) -> Self {
        Self::Delegations(payload)
    }
}

#[rustfmt::skip]
impl From<Projection> for ObservationResult {
    fn from(payload: Projection) -> Self {
        Self::Projection(payload)
    }
}

#[rustfmt::skip]
impl From<Observe> for Input {
    fn from(payload: Observe) -> Self {
        Self::Observe(payload)
    }
}

#[rustfmt::skip]
impl From<Resolve> for Input {
    fn from(payload: Resolve) -> Self {
        Self::Resolve(payload)
    }
}

#[rustfmt::skip]
impl From<Project> for Input {
    fn from(payload: Project) -> Self {
        Self::Project(payload)
    }
}

#[rustfmt::skip]
impl From<Validate> for Input {
    fn from(payload: Validate) -> Self {
        Self::Validate(payload)
    }
}

#[rustfmt::skip]
impl From<Observed> for Output {
    fn from(payload: Observed) -> Self {
        Self::Observed(payload)
    }
}

#[rustfmt::skip]
impl From<Resolved> for Output {
    fn from(payload: Resolved) -> Self {
        Self::Resolved(payload)
    }
}

#[rustfmt::skip]
impl From<Projected> for Output {
    fn from(payload: Projected) -> Self {
        Self::Projected(payload)
    }
}

#[rustfmt::skip]
impl From<Validated> for Output {
    fn from(payload: Validated) -> Self {
        Self::Validated(payload)
    }
}

#[rustfmt::skip]
impl From<RequestRejected> for Output {
    fn from(payload: RequestRejected) -> Self {
        Self::RequestRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_OBSERVE: u64 = 0x0000000000000000;
    pub const INPUT_RESOLVE: u64 = 0x0001000000000000;
    pub const INPUT_PROJECT: u64 = 0x0002000000000000;
    pub const INPUT_VALIDATE: u64 = 0x0003000000000000;
    pub const OUTPUT_OBSERVED: u64 = 0x0100000000000000;
    pub const OUTPUT_RESOLVED: u64 = 0x0101000000000000;
    pub const OUTPUT_PROJECTED: u64 = 0x0102000000000000;
    pub const OUTPUT_VALIDATED: u64 = 0x0103000000000000;
    pub const OUTPUT_REQUEST_REJECTED: u64 = 0x0104000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Observe,
    Resolve,
    Project,
    Validate,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Observed,
    Resolved,
    Projected,
    Validated,
    RequestRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Observe(_) => InputRoute::Observe,
            Self::Resolve(_) => InputRoute::Resolve,
            Self::Project(_) => InputRoute::Project,
            Self::Validate(_) => InputRoute::Validate,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Observe(_) => short_header::INPUT_OBSERVE,
            Self::Resolve(_) => short_header::INPUT_RESOLVE,
            Self::Project(_) => short_header::INPUT_PROJECT,
            Self::Validate(_) => short_header::INPUT_VALIDATE,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_OBSERVE => Ok(InputRoute::Observe),
            short_header::INPUT_RESOLVE => Ok(InputRoute::Resolve),
            short_header::INPUT_PROJECT => Ok(InputRoute::Project),
            short_header::INPUT_VALIDATE => Ok(InputRoute::Validate),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Observed(_) => OutputRoute::Observed,
            Self::Resolved(_) => OutputRoute::Resolved,
            Self::Projected(_) => OutputRoute::Projected,
            Self::Validated(_) => OutputRoute::Validated,
            Self::RequestRejected(_) => OutputRoute::RequestRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Observed(_) => short_header::OUTPUT_OBSERVED,
            Self::Resolved(_) => short_header::OUTPUT_RESOLVED,
            Self::Projected(_) => short_header::OUTPUT_PROJECTED,
            Self::Validated(_) => short_header::OUTPUT_VALIDATED,
            Self::RequestRejected(_) => short_header::OUTPUT_REQUEST_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_OBSERVED => Ok(OutputRoute::Observed),
            short_header::OUTPUT_RESOLVED => Ok(OutputRoute::Resolved),
            short_header::OUTPUT_PROJECTED => Ok(OutputRoute::Projected),
            short_header::OUTPUT_VALIDATED => Ok(OutputRoute::Validated),
            short_header::OUTPUT_REQUEST_REJECTED => Ok(OutputRoute::RequestRejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Observe",
        "Resolve",
        "Project",
        "Validate",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
